layout_spectrum: 0.9914867838378996
typography_spectrum: 0.5548955369740725
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8649002774618566
  lightness: 0.27588979923166335
  saturation: 0.3346340812277049
  rhythmicContrast: 0.3690628153271973
content_rating:
  adult: false
opengraph:
  type: ''
  appId: ''
author:
  name: 'Martin Apolonia Årdal '
  url: apolonia.no
  email: martin.ardal@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e94f7f1e-4f8a-4e74-bd4a-698ce1dbf08d.jpg
name: Apolonia Agritech
navigation:
  - name: 3D printer live
    url: 'http://158.38.34.183/#'
    type: external
  - name: Facebook page
    url: 'https://www.facebook.com/ApoloniaAquaponics/'
    type: external
title: heads will roll
description: and you will grow
