typography_spectrum: 0.6657475552055985
content_rating:
  adult: false
color:
  brandColors:
    - '#5A1F00'
    - '#D1570D'
    - '#FDE792'
    - '#477725'
    - '#A9CC66'
  brandStrength: 0.5796120520681143
  lightness: 0.4631586489267647
  saturation: 0.7544056640472263
  rhythmicContrast: 0.8608225132338703
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.9813400227576494
author:
  name: 'Martin Apolonia Årdal '
  url: apolonia.no
  email: martin.ardal@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e94f7f1e-4f8a-4e74-bd4a-698ce1dbf08d.jpg
name: Apolonia Agritech
title: heads will roll
description: and you will grow
